### ISSUE TITLE
Design => Free Shirt

### ISSUE THREAD

**Issue by arb** [continuationlabs/hapi-setup#28]
We really need your help making hapi-setup look awesome for the version 3 milestone! To that end, we are prepared to ship you, free of charge, one official hapijs.com t-shirt for your help! You'll also be listed as a contributor on GitHub and if you represent a company, your company name and logo can be featured on the GitHub README.md file. As an added bonus, we'll even throw in a signed copy of our book [Full Stack JavaScript Development With MEAN](http://www.amazon.com/Full-Stack-JavaScript-Development-MEAN/dp/0992461251)!
## Rules
1. Use the existing build pipeline as it currently stands. No new tools (gulp and grunt I'm looking at you).
2. Use Stylus and the provided plugins that are already available(AutoPrefixer, Axis, Rupture, and jeet). If you can make a compelling argument for another or different plugin, we're certainly open to that conversation.
3. It must be responsive.
4. Use good CSS judgement.
5. Currently, we are only looking for CSS styling, no JavaScript.
6. Use Jade.
7. We're only interested in real, modern browsers. Let's call it IE11 and up.
## Submitting

To submit your style for consideration, open a regular pull request as you normally would. Please include screen shots in the pull request so we can see what it looks like without having to pull down and run the code. In the event of multiple submissions, the one we think looks the best will be declared the winner and will receive the free shirt.

As far as "what should it look like", that is entirely up to you! We ask that you don't style it similar to your company's color and theme, but beyond that, the sky is the limit. If you want, you can style it with similar colors and concept as hapijs.com, but that is absolutely not required. 

Also, please note that this software is published under the [MIT license](https://opensource.org/licenses/MIT). Be sure you are OK with contributing to a project with that license before opening a pull request. 
## Questions
1. How do I make it work? Pull the code down and run `npm install` followed by `npm start`. You can then point a web browser to "http://localhost:8888/setup" to see UI. If you're interested in the RAW object, point a browser to "http://localhost:8888".
2. What should I do about "[object Object]"? At the moment, nothing. Style it as it is, that's something for "down the road" to explode those objects.
3. Can I change the markup? Yes. You are the expert here. Change the DOM to work for you and to be more semantically correct.
4. What sizes do you have? We have Men's M and XL and Woman's M.

`n`. _More to come as submissions come in_

**Comment by krishnay** [comment]
@arb do you have any design in specific?  I can help you in css style changes

**Comment by arb** [comment]
@krishnay, nope. Completely up to you. Like I said above, you can take queues from hapijs.com, but you don't have to. 

We can make CSS style changes too, it's coming up with designs where we really need the help :smile:

**Comment by cjihrig** [comment]
`hapi-swagger` is another alternative to look at for styling.

**Comment by krishnay** [comment]
@arb I am not seeing any head branch

**Comment by krishnay** [comment]
@arb  I downloaded the project and did npm start but end up with the errors..

**Comment by cjihrig** [comment]
git clone, following by npm i and npm start worked for me.

**Comment by krishnay** [comment]
@cjihrig yes i did git clone and I cd'd to the happy-setup folder and did npm start got some errors

**Comment by cjihrig** [comment]
Can you paste the errors here?

**Comment by krishnay** [comment]
> hapi-setup@2.0.1 start /Users/Krishna/Documents/projecthelp/hapi-setup
> node dev-server & npm run webpack

module.js:338
    throw err;
    ^

Error: Cannot find module 'hapi'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Krishna/Documents/projecthelp/hapi-setup/dev-server.js:4:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

> hapi-setup@2.0.1 webpack /Users/Krishna/Documents/projecthelp/hapi-setup
> webpack -w -c -v

sh: webpack: command not found

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hapi-setup@2.0.1 webpack: `webpack -w -c -v`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the hapi-setup@2.0.1 webpack script 'webpack -w -c -v'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hapi-setup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -w -c -v
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hapi-setup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hapi-setup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Krishna/Documents/projecthelp/hapi-setup/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! hapi-setup@2.0.1 start: `node dev-server & npm run webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hapi-setup@2.0.1 start script 'node dev-server & npm run webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hapi-setup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dev-server & npm run webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hapi-setup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hapi-setup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by cjihrig** [comment]
Did you run `npm install`?

**Comment by krishnay** [comment]
@cjihrig done working like charm. Now the project is running which url I need to hit to see the project

**Comment by cjihrig** [comment]
> You can then point a web browser to "http://localhost:8888/setup" to see UI. If you're interested in the RAW object, point a browser to "http://localhost:8888".

**Comment by krishnay** [comment]
@cjihrig what is the goal on the setup page?

**Comment by cjihrig** [comment]
`hapi-setup` lets you visualize the environment that a hapi server is running. Right now, the page is about as ugly and simple as can be. The goal of this issue is simply to make the page more enjoyable to look at :-)

You might want to check out http://www.hapijs.com/ or https://github.com/glennjones/hapi-swagger for design ideas.

**Comment by krishnay** [comment]
@cjihrig understood we need to make the setup page more pretty...When I need to start styling the setup page?

**Comment by cjihrig** [comment]
At your earliest convenience.

**Comment by krishnay** [comment]
@cjihrig  what was the reason behind using stylus?

**Comment by krishnay** [comment]
@arb @cjihrig  seems like I don't have access to commit the changes.

**Comment by arb** [comment]
@krishnay this issue is for discussing the contest and the task at hand. This issue should *not* be used as a general help bucket. If you have specific questions related to this plugin, please open up new issues, rather than using this one.

**Comment by krishnay** [comment]
@arb ok i was not able to commit my changes

**Comment by cjihrig** [comment]
You should fork the repo on GitHub. Pull the code down to your local machine (which I assume you've already done). Make changes and commit them locally. Push the changes up to your GitHub fork, then make a pull request back to this repo.
